apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.8.0_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=127.0.0.1
    - --allow-privileged=true
    - --secure-port=6443
    - --admission-control=""
    - --service-cluster-ip-range=10.254.0.0/16
    - --etcd-servers=http://127.0.0.1:4002
    - --cloud-provider=aws
    - --tls-cert-file=/etc/kubernetes/ssl/server.cert
    - --tls-private-key-file=/etc/kubernetes/ssl/server.key
    - --client-ca-file=/etc/kubernetes/ssl/ca.crt
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 6443
      hostPort: 6443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
  - name: etcd
    image: quay.io/coreos/etcd:v3.1.10
    command:
    - etcd
    - --data-dir=/var/lib/etcd
    - --advertise-client-urls=http://127.0.0.1:4002
    - --listen-client-urls=http://127.0.0.1:4002
    - --listen-peer-urls=http://127.0.0.1:2381
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-datadir
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /var/lib/etcd
    name: etcd-datadir
