apiVersion: v1
kind: Service
metadata:
  name: aws-lb-nginx
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: nginx
  type: LoadBalancer
